### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by riversn** [bradmartin333/SEYR#131]
Had some new people try nice SEYR/everything. a few comments:

**Make the boxes in SEYR clickable & draggable.** multiple people have expected this immediately and disliked having to use the little values in the boxes at the bottom.

From a new user standpoint, the whole 'why do we need two separate sides' is a thing... like, why do we need to make an inspection box on the right side of the page (a second time) instead of all on the left side? on one hand there's not a clear label/distinguisher for the right side so it's not clear how to use it the first time you look at it. But overall, I'm not sure how to streamline it to make it any better.

No more px/um offset of the boxes, maybe it's nice to have at somepoint, but it's not particularly accurate or meaningful. Almost always, in SEYR Panel we're going to Tools -> px/um and setting it to 1.000 instead of 10.watever. Or atleast just set it to default 1 and maybe the user could change it if they want?

As SEYR runs it'd be great to display a small distribution chart of the current run so the user can see how inspection units are being scored. Right now, if the user wants to check if the threshold works real well, they have to run the seyr recipe, stop it, parse it with xfersuite, and then check the distribution of the scores to see if there's good separation. Would be great to see a simplified version as it runs maybe?

**Comment by bradmartin333** [comment]
**click & drag** - I tested this a while ago and, unfortunately, the core architecture of the project makes this very faulty. I can't find the closed issue that pertains to this, but the issue stems from **px/um** 
=== If you _never ever never_ need px/um and it can always be 1, then yes, I can add click & drag. I think the reason for px/um was so the numbers in the UI correlate with the real world dimensions of things, but I know that it never lines up perfectly

By 2 separate sides, you mean the "Feature Grid" and "Feature Layout" (Those labels were added in another issue I cannot find) sides of the SEYR composer? The reason also relates to the core architecture and to prevent the need for zoom/pan for teaching features. Nowadays, I could allow zoom/pan and a single window - but I think it would be easy to get lost... and then people would want a minimap and such ahahha

The default px/um can be set through SEYRpanel: `SEYRCh.SetPixelsPerMicron(1.303f);` is in my example, but it could be `1f`

I like the idea of the streaming distribution chart - I can play around with that, but I cannot guarantee PC performance won't be hit since I can't test on your systems anymore

let me know if I missed anything and what your thoughts are and then I can break this into individual issues

**Comment by bradmartin333** [comment]
I think the boxes are at least clickable, no? maybe you have to use the shortcut for one of the toolbar tools first? Will check when I get everything running again

**Comment by riversn** [comment]
Xfersuite is used to parse the data, JMP is used just to display yields graphically in a pretty format. The data collection and everything is still on XferSuite

**Comment by bradmartin333** [comment]
Raw data distribution chart is quite straightforward - just need a mockup of what you want it to look like

Not sure what you need from this specific issue, so breakout into smaller issues when you get the time
